---
title: "Baseline Outbreak Dynamics"
author: "Odin Rumianowski"
date: "2024-11-02"
output: html_document
---

```{r}
setwd("C:/Data/1_Adminitratif/Emploi/cornell/02_projet/hpai_mitigation/02_models")
```


```{r}
library(ppcor)
library(GGally)
library(ggplot2)
library(tidyverse)
library(forcats)
```


```{r}
load("simulation_dt/simulation_dt_1000it_cluster_1.RData")
simulation_dt1 = simulation_dt
load("simulation_dt/simulation_dt_1000it_ordi_1.RData")
simulation_dt2 = simulation_dt
load("simulation_dt/simulation_dt_10000it_cluster_1.RData")
simulation_dt3 = simulation_dt
load("simulation_dt/simulation_dt_2000it_cluster_1.RData")
simulation_dt4 = simulation_dt
simulation_dt = rbind(simulation_dt1,
                      simulation_dt2,
                      simulation_dt3,
                      simulation_dt4)
```


```{r}
param = c("initial_number_infected_breeders_A", "initial_number_infected_breeders_B", "initial_number_infected_breeders_C", "initial_number_breeders_A",         
          "initial_number_breeders_B",          "initial_number_breeders_C",          "dispersal_reaction_time",            "dispersal_date",                    
          "hatching_date",                      "tau",                                "total_time",                         "prop_dispersal",                    
          "beta_E_colony",                      "beta_I_colony",                      "incubation_period",                  "eta",                               
          "infectious_period",                  "adult_mortality",                    "nestling_mortality",                 "avrg_stay_B_colony",                
          "avrg_stay_B_sea",                    "avrg_stay_NB_colony",                "avrg_stay_NB_sea",                   "theta",                             
          "psi",                                "hatching_sd",                        "reaching_repro_prob",                "prob_detection"  )

param_evaluated = c("initial_number_infected_breeders_A",        
                    "hatching_date",                      "prop_dispersal",                    
                    "beta_I_colony",                      "incubation_period",                                              
                    "infectious_period",                  "adult_mortality",   
                    "nestling_mortality",                         
                    "avrg_stay_NB_sea",                   "theta",                             
                    "reaching_repro_prob",                "prob_detection",
                    
                    "dispersal_reaction_time",
                    "prob_detection")
```


```{r}
dt <- simulation_dt %>%
  dplyr::select(1:32) %>% 
  pivot_wider(
    names_from = scenario,  
    values_from = c(nb_adults_equi, nb_infected_colonies, infected_X_time), 
    names_glue = "{scenario}_{.value}" 
  ) %>% 
  unnest(cols = everything()) %>% 
  mutate(BO_P2_nb_adults_equi = BO_nb_adults_equi - P2_nb_adults_equi) %>% 
  mutate(BO_RS_nb_adults_equi = BO_nb_adults_equi - RS_nb_adults_equi) %>% 
  mutate(BO_P2_infected_X_time = BO_infected_X_time - P2_infected_X_time) %>% 
  mutate(BO_RS_infected_X_time = BO_infected_X_time - RS_infected_X_time)
```


```{r}
partial_cor = function(data, param_evaluated, selected_output){
    
    dt_cor = data %>% 
      dplyr::select(all_of(c(param_evaluated, selected_output)))

    pcor_results  = pcor(dt_cor)

    pcor_matrix <- pcor_results$estimate %>% 
      as.matrix() %>% 
      data.frame() %>% 
      dplyr::select(selected_output) %>% 
      arrange(desc(!!sym(selected_output))) 
    
    return(pcor_matrix)
  }
```


```{r}
res_ENLA = cbind(
partial_cor(data = dt,
            param_evaluated = param_evaluated,
            selected_output = "BO_nb_adults_equi"),
partial_cor(data = dt,
            param_evaluated = param_evaluated,
            selected_output = "BO_P2_nb_adults_equi"),
partial_cor(data = dt,
            param_evaluated = param_evaluated,
            selected_output = "BO_RS_nb_adults_equi")
) %>% 
  as.data.frame() %>% 
  slice(-1) %>%
  rownames_to_column(var = "param") %>% 
  pivot_longer(-param) %>%
  mutate(param = fct_reorder(param, value, .desc = TRUE))
```


```{r}
res_infected = cbind(
  partial_cor(data = dt,
              param_evaluated = param_evaluated,
              selected_output = "BO_infected_X_time")
  ,
  partial_cor(data = dt,
              param_evaluated = param_evaluated,
              selected_output = "BO_P2_infected_X_time")
  ,
  partial_cor(data = dt,
              param_evaluated = param_evaluated,
              selected_output = "BO_RS_infected_X_time")
) %>% 
  as.data.frame() %>% 
  slice(-1) %>%
  rownames_to_column(var = "param") %>% 
  pivot_longer(-param) %>%
  mutate(param = fct_reorder(param, value, .desc = TRUE))
```


```{r}
ggplot() +
  geom_point(data = res_ENLA, aes(x = param, y = value)) +
  facet_wrap(~ name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}

ggplot() +
  geom_point(data = res_ENLA, aes(x = param, y = value, color = name)) +
  #facet_wrap(~ name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```


```{r}
ggplot() +
  geom_point(data = res_infected, aes(x = param, y = value)) +
  facet_wrap(~ name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```


## Proxies - One colony

```{r}

setwd("C:/Data/1_Adminitratif/Emploi/cornell/02_projet/hpai_mitigation/02_models")

library(tidyverse)
library(rpart)				       
library(rattle)					
library(rpart.plot)			
library(RColorBrewer)				
library(party)					
library(partykit)			
library(caret)	

load("simulation_dt/dt_cluster_3_1E4_for_one_col_v1.RData")


dt = simulation_dt %>% 
  mutate(S_adult = S_a_B + S_b_B + S_c_B + S_a_NB + S_b_NB + S_c_NB) %>% 
  mutate(R_adult = R_a_B + R_b_B + R_c_B + R_a_NB + R_b_NB + R_c_NB) %>% 
  mutate(D_adult = D_a_B + D_b_B + D_c_B + D_a_NB + D_b_NB + D_c_NB) %>% 
  mutate(prop_R = R_adult / (R_adult + S_adult)) %>% 
  mutate(prop_D = D_adult / (D_adult + R_adult + S_adult)) %>% 
  mutate(S_a = S_a_B + S_a_NB) %>% 
  mutate(R_a = R_a_B + R_a_NB) %>% 
  mutate(D_a = D_a_B + D_a_NB) %>% 
  mutate(prop_R_a = R_a / (R_a + S_a)) %>% 
  mutate(prop_D_a = D_a / (D_a + R_a + S_a)) %>% 
  subset(., scenario == "BO") %>% 
  subset(., initial_number_infected_breeders_A != 0) %>% 
  mutate(ad_mortality = cut(adult_mortality,
                            breaks = 3, 
                            labels = c("Low mortality", "Medium mortality", "High mortality")))%>% 
  mutate(transmission_rate = cut(log(beta_I_colony),
                            breaks = 3, 
                            labels = c("Low TR", "Medium TR", "High TR")))




ggplot()+
  geom_point(data = dt, aes(x = prop_D_a, y = prop_R_a, color = beta_I_colony )) +
  scale_color_gradient2(trans = "log", low = "blue", mid = "yellow", high = "red", midpoint = log(0.1)) +
  facet_wrap(~ad_mortality)


ggplot()+
  geom_point(data = dt, aes(x = prop_D_a, y = prop_R_a, color = adult_mortality )) +
  scale_color_gradient2(low = "blue", mid = "yellow", high = "red", midpoint = 0.6) +
  facet_wrap(~transmission_rate)



dt2 = dt %>% 
  subset(., prop_R_a < 0.25)%>% 
  subset(., prop_R_a > 0.00)



ggplot()+
  geom_point(data = dt2, aes(x = prop_D_a, y = prop_R_a, color = beta_I_colony )) +
  scale_color_gradient2(trans = "log", low = "blue", mid = "yellow", high = "red", midpoint = log(0.06)) +
  #scale_color_gradient2(low = "blue", mid = "yellow", high = "red", midpoint = 0.3) +
  facet_wrap(~ad_mortality)


ggplot()+
  geom_point(data = dt2, aes(x = prop_D_a, y = prop_R_a, color = beta_I_colony )) +
  scale_color_gradient2(trans = "log", low = "blue", mid = "yellow", high = "red", midpoint = log(0.06))
 # +facet_wrap(~ad_mortality)



```

